[package]
name = "nuon"
version = "0.1.0"
edition = "2021"

[dependencies]
profiling.workspace = true
euclid.workspace = true
smallvec = "1.13.2"
thunderdome = "0.6"
dpi = "0.1.1"
winit = { version = "0.30", features = ["rwh_05"] }
