language: c

compiler:
  - gcc

sudo: required

dist: trusty

before_script:
   - sudo apt-get update -qq
   - sudo apt-get install -qq autoconf
   - sudo apt-get install -qq libgtkmm-2.4-dev
   - sudo apt-get install -qq libgconfmm-2.6-dev
   - sudo apt-get install -qq libgtkglextmm-x11-1.2-dev
   - sudo apt-get install -qq libasound2-dev

script:
  - autoconf --version
  - mkdir m4 && ./autogen.sh && make && make check


