name: Build

on: 
  push:
    branches:    
      - master
  pull_request:
  workflow_dispatch:
  
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/ubuntu
      - name: ls
        run: ls -l app.zip

  build_ubuntu_recorder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/ubuntu-recorder
      - name: ls
        run: ls -l app.zip

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/windows
      - name: ls
        run: ls -l target/release/neothesia.exe

  build_windows_recorder:
    runs-on: windows-latest

    env:
      FFMPEG_DOWNLOAD_URL: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
      
    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/windows-recorder
      - name: ls
        run: ls -l target/release/neothesia-cli.exe

  build_macos:
    runs-on: macos-latest

    env:
      MACOSX_DEPLOYMENT_TARGET: 10.12

    steps:
      - uses: actions/checkout@v4
      - id: Build
        uses: ./.github/actions/macos
      - name: ls
        run: ls -l .github/app/app.zip

